//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanQuanAo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDatHangs = new HashSet<ChiTietDatHang>();
            this.PhanHois = new HashSet<PhanHoi>();
        }
    
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string MaNhanHieu { get; set; }
        public string MaLoaiSanPham { get; set; }
        public string NoiSanXuat { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string TinhTrang { get; set; }
        public string MoTa { get; set; }
        public string AnhSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatHang> ChiTietDatHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhanHieu NhanHieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
    }
}
